function [x_opt,status] = PaDOA_MINLP(minlp,loc_sol,z,lb_minlp,ub_minlp,lbg,ubg)
    if isempty(z)
        sol = minlp('x0', loc_sol,...
                  'lbx', lb_minlp,...
                  'ubx', ub_minlp,...
                  'lbg', lbg, ...
                  'ubg', ubg);
    else
        sol = minlp('x0', loc_sol,...
                  'p',   z,...
                  'lbx', lb_minlp,...
                  'ubx', ub_minlp,...
                  'lbg', lbg, ...
                  'ubg', ubg);
    end
    status = string(minlp.stats.return_status);
    x_opt = sol.x;
end